version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::061051222764:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-fF9jcSYWFVLS"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::061051222764:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-y0Z4xPEFy9IS"
cloudformation_execution_role = "arn:aws:iam::061051222764:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-9OfeHY8tqr0V"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-umyomanajhev"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::061051222764:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-wRsrb2k67D9x"
cloudformation_execution_role = "arn:aws:iam::061051222764:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-UEbcRTpZbMn4"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-jqkq5hpfhupg"
image_repository = ""
region = "us-east-1"
